FROM python:3.9-slim

WORKDIR /app
ENV PYTHONPATH="/app"

COPY src ./src
COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

# Make sure the db folder exists
RUN mkdir -p /app/src/db

CMD ["python", "-u", "src/generate_db.py"]
