services:
  db-builder:
    build:
      context: .
      dockerfile: Dockerfile.db
    volumes:
      - ./src/data:/app/src/data
      - actors_db:/app/src/db
    restart: "no"
    networks:
      - backend

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    volumes:
      - actors_db:/app/src/db
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      db-builder:
        condition: service_completed_successfully
    networks:
      - backend

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    depends_on:
      db-builder:
        condition: service_completed_successfully
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - backend

  message_consumer:
    build:
      context: .
      dockerfile: Dockerfile.message_consumer
    entrypoint: ["python", "-m", "src.message_consumer.run_message_processor"]
    container_name: message_consumer
    depends_on:
      db-builder:
        condition: service_completed_successfully
    environment:
      RABBITMQ_HOST: rabbitmq
      PYTHONUNBUFFERED: "1"
    volumes:
      - actors_db:/app/src/db
    networks:
      - backend
    restart: always

networks:
  backend:
    driver: bridge

volumes:
  actors_db:
