FROM python:3.9-slim

WORKDIR /app

ENV PYTHONPATH="/app"

COPY requirements.txt .
COPY src ./src

RUN pip install --no-cache-dir -r requirements.txt


CMD ["python", "-m", "src.message_consumer.run_message_processor"]